---
# tasks file for provision/roles/poc-labs
- name: "Install Web Service"
  package:
    name: "{{ hello_web.package }}"
    state: present
- name: "Start Web Service"
  service:
    name: "{{ hello_web.service }}"
    state: started
    enabled: yes
- name: "Copy Web Content"
  copy:
    src: "{{ role_path }}/files/index.html"
    dest: "{{ hello_web.docroot }}/index.html"

# - name: Install conjure-up for Canonical Kubernetes
#   snap:
#     name: microk8s
#     classic: yes


# ---

# - name: "Including distro-specific variables"
#   include_vars: "vars_{{ ansible_distribution }}.yml"

# - name: "Setting things up for {{ ansible_distribution }}"
#   include: "setup_{{ ansible_distribution }}.yml"

# ---

# - name: "Installing packages"
#   apt:
#     name: "{{ mage_packages }}"
#     state: latest
#     update_cache: true
#     cache_valid_time: 3600


# ---
# mage_packages:
#   - squashfuse
#   - snapd
#   - fuse